config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#add', as: :new
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#remove', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def add
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def remove
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/add.html.erb
<%= form_for(@task) do |task| %>
  <%= task.label :title %>
  <%= task.text_field :title %>

  <%= task.label :details %>
  <%= task.text_field :details %>

  <%= task.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

<!-- <form method="patch" action="tasks/1/update"></form>
 -->

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>

  <p> <input type= checkbox ><%= link_to task.title, task_path(task.id) %><%= if task.completed
    ""
    else
    ""
   end %>
  </p>

  <p><%= task.details %></p>
  <%= link_to "Remove a task", delete_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

  <%= link_to "Edit a task", edit_path(task),
      method: :get %>

<% end %>


<%= link_to "Add a task", new_path,
      method: :get %>

app/views/tasks/show.html.erb
<h1>My selected task</h1>

<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed == false %>
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    This task is not completed yet
  </label>
</div>

<%end %>

<%= link_to "Back to list", tasks_path %>